[basic_auth]
enabled  = false
username = admin
password = admin

[api]
port            = 8180
api_key_enabled = false
api_key         = your_api_key

[ui]
port    = 8181
name    = WHEREISIT
link    = https://github.com/bitcrushtesting/whereisit
logo    =
; Set api_url when API and UI run on different ports, e.g. http://yourserver:8180
api_url =
